@echo off
rem deploy.cmd - the WinPE task sequence. Injected into X:\Windows\System32 by
rem wimboot and started by winpeshl.ini. Plain cmd; edit it on the server and
rem reboot the target, nothing is rebuilt.
rem
rem It wipes a disk ONLY when machines/<id>.cfg on the server says MODE=deploy.
rem Every step reports start and ok/fail to the server (GET /beacon) and pushes
rem its logs (PUT /uploads/<id>/<run>/); see PLAN.md section 3.2.
setlocal EnableExtensions EnableDelayedExpansion

set PDT=X:\pdt
if not exist %PDT% mkdir %PDT%
set LOG=%PDT%\ts.log
set CURL=%SystemRoot%\System32\curl.exe -sS

rem id.cmd is generated by the server from what iPXE saw: SRV, ID, MAC.
call %SystemRoot%\System32\id.cmd
if not defined SRV (
  echo [pdt] id.cmd is missing or empty: this boot did not come through boot.ipxe.
  goto :shell
)
set RUN=%RANDOM%%RANDOM%

rem Defaults; machines/<id>.cfg may override them.
set MODE=shell
set IMAGE=base.wim
set UNATTEND=default.xml
set DRIVERS=
set DISKPART=uefi-gpt.txt

echo [pdt] id %ID%  run %RUN%  server %SRV%
echo [pdt] id %ID% run %RUN% server %SRV% >>%LOG%
echo [pdt] starting the network (wpeinit)...
wpeinit >>%LOG% 2>&1

set /a TRIES=0
:waitnet
%CURL% -f -o nul --max-time 3 "%SRV%/health" >nul 2>&1 && goto :netok
set /a TRIES+=1
if %TRIES% geq 60 (
  echo [pdt] the server %SRV% did not answer for two minutes.
  ipconfig >>%LOG% 2>&1
  goto :shell
)
ping -n 2 127.0.0.1 >nul
goto :waitnet
:netok

rem ---------------------------------------------------------------- ts-start
for %%k in (SystemManufacturer SystemProductName) do (
  for /f "tokens=2,*" %%a in ('reg query HKLM\HARDWARE\DESCRIPTION\System\BIOS /v %%k 2^>nul ^| find "%%k"') do set "%%k=%%b"
)
%CURL% -f -o %PDT%\machine.cfg "%SRV%/machines/%ID%.cfg" >>%LOG% 2>&1
if errorlevel 1 (
  echo [pdt] no machines/%ID%.cfg on the server: this machine is not listed.
  echo [pdt] no machine cfg, MODE=shell >>%LOG%
) else (
  for /f "usebackq eol=# tokens=1,* delims==" %%a in ("%PDT%\machine.cfg") do (
    for %%k in (MODE IMAGE UNATTEND DRIVERS DISKPART) do if /i "%%a"=="%%k" set "%%k=%%b"
  )
)
call :beacon ts-start ok "mode=%MODE%" "product=!SystemProductName!" "mfr=!SystemManufacturer!" "mac=%MAC%"

if /i not "%MODE%"=="deploy" (
  call :beacon shell ok "mode=%MODE%"
  call :push
  echo [pdt] MODE=%MODE%: nothing will be changed on this machine.
  goto :shell
)

echo [pdt] MODE=deploy  image %IMAGE%  unattend %UNATTEND%  drivers "%DRIVERS%"
echo [pdt] THIS WIPES DISK 0.

rem --------------------------------------------------------------- preflight
rem Before anything is destroyed: is every file this install needs on the
rem server? A typo in the cfg must not cost the machine its disk.
call :begin preflight
set RC=0
set MISSING=
for %%u in ("ts/diskpart/%DISKPART%" "images/%IMAGE%" "unattend/%UNATTEND%" "post/beacon.cmd" "post/firstlogon.cmd") do (
  %CURL% -f -I -o nul "%SRV%/%%~u" >>%LOG% 2>&1 || (set RC=1& set "MISSING=!MISSING! %%~u")
)
if defined DRIVERS (
  %CURL% -f -I -o nul "%SRV%/drivers/%DRIVERS%.wim" >>%LOG% 2>&1 || (set RC=1& set "MISSING=!MISSING! drivers/%DRIVERS%.wim")
)
if not !RC!==0 echo [pdt] not on the server:!MISSING!
if not !RC!==0 echo [pdt] not on the server:!MISSING! >>%LOG%
call :end !RC! "msg=missing:!MISSING!" || goto :failed

rem -------------------------------------------------------------------- disk
call :begin disk
set RC=0
%CURL% -f -o %PDT%\diskpart.txt "%SRV%/ts/diskpart/%DISKPART%" >>%LOG% 2>&1 || set RC=!errorlevel!
if !RC!==0 (diskpart /s %PDT%\diskpart.txt >>%LOG% 2>&1 || set RC=!errorlevel!)
if !RC!==0 (mkdir W:\Scratch >>%LOG% 2>&1 || set RC=!errorlevel!)
call :end !RC! || goto :failed

rem ---------------------------------------------------------------- download
call :begin download
set RC=0
%CURL% -f --retry 2 -o W:\image.wim "%SRV%/images/%IMAGE%" >>%LOG% 2>&1 || set RC=!errorlevel!
call :end !RC! || goto :failed

rem ------------------------------------------------------------------- apply
call :begin apply
set RC=0
dism /apply-image /imagefile:W:\image.wim /index:1 /applydir:W:\ /scratchdir:W:\Scratch /logpath:%PDT%\dism.log >>%LOG% 2>&1 || set RC=!errorlevel!
del W:\image.wim >>%LOG% 2>&1
call :end !RC! || goto :failed

rem ----------------------------------------------------------------- drivers
if not defined DRIVERS goto :nodrivers
call :begin drivers
set RC=0
%CURL% -f -o W:\drivers.wim "%SRV%/drivers/%DRIVERS%.wim" >>%LOG% 2>&1 || set RC=!errorlevel!
if !RC!==0 (mkdir W:\Drivers >>%LOG% 2>&1 || set RC=!errorlevel!)
if !RC!==0 (dism /apply-image /imagefile:W:\drivers.wim /index:1 /applydir:W:\Drivers /scratchdir:W:\Scratch /logpath:%PDT%\dism.log >>%LOG% 2>&1 || set RC=!errorlevel!)
if !RC!==0 (dism /image:W:\ /add-driver /driver:W:\Drivers /recurse /scratchdir:W:\Scratch /logpath:%PDT%\dism.log >>%LOG% 2>&1 || set RC=!errorlevel!)
rmdir /s /q W:\Drivers >>%LOG% 2>&1
del W:\drivers.wim >>%LOG% 2>&1
call :end !RC! || goto :failed
:nodrivers

rem -------------------------------------------------------------------- boot
call :begin boot
set RC=0
bcdboot W:\Windows /s S: /f UEFI >>%LOG% 2>&1 || set RC=!errorlevel!
call :end !RC! || goto :failed

rem ---------------------------------------------------------------- unattend
rem Also leaves C:\pdt\ on the installed disk: id.cmd (SRV, ID, MAC, RUN) plus
rem the beacon and first-logon scripts, so the installed OS continues this run.
call :begin unattend
set RC=0
if not exist W:\Windows\Panther mkdir W:\Windows\Panther >>%LOG% 2>&1
%CURL% -f -o W:\Windows\Panther\unattend.xml "%SRV%/unattend/%UNATTEND%" >>%LOG% 2>&1 || set RC=!errorlevel!
if not exist W:\pdt mkdir W:\pdt >>%LOG% 2>&1
copy /y %SystemRoot%\System32\id.cmd W:\pdt\id.cmd >>%LOG% 2>&1 || set RC=!errorlevel!
>>W:\pdt\id.cmd echo set "RUN=%RUN%"
%CURL% -f -o W:\pdt\beacon.cmd "%SRV%/post/beacon.cmd" >>%LOG% 2>&1 || set RC=!errorlevel!
%CURL% -f -o W:\pdt\firstlogon.cmd "%SRV%/post/firstlogon.cmd" >>%LOG% 2>&1 || set RC=!errorlevel!
rmdir /s /q W:\Scratch >>%LOG% 2>&1
call :end !RC! || goto :failed

call :beacon ts-done ok
call :push
echo [pdt] done - rebooting into the installed system.
wpeutil reboot
exit /b 0

rem ================================================================ helpers
:failed
echo.
echo [pdt] step "%STEP%" FAILED. The server has the fail event and the logs.
echo [pdt] log: %LOG%   dism log: %PDT%\dism.log
:shell
echo [pdt] shell. Server: %SRV%   id: %ID%
exit /b 1

rem :begin <step>   announce a step and send ev=start
:begin
set STEP=%~1
echo [pdt] %STEP% ...
echo.>>%LOG%
echo [pdt] ===== %STEP% >>%LOG%
call :beacon %STEP% start
exit /b 0

rem :end <rc> ["msg=..."]   send ev=ok or ev=fail (with rc and msg) for the current step, push logs, return rc
:end
if "%~1"=="0" (call :beacon %STEP% ok) else (call :beacon %STEP% fail "rc=%~1" %2)
call :push
exit /b %~1

rem :beacon <step> <ev> ["key=value" ...]   (quote every key=value)
:beacon
set "B=--data-urlencode id=%ID% --data-urlencode run=%RUN% --data-urlencode step=%~1 --data-urlencode ev=%~2"
echo [pdt] beacon %~1 %~2 >>%LOG%
shift
shift
:beacon_more
if "%~1"=="" goto :beacon_send
set "B=%B% --data-urlencode "%~1""
shift
goto :beacon_more
:beacon_send
%CURL% -G "%SRV%/beacon" %B% -o nul --max-time 15 >>%LOG% 2>&1
exit /b 0

rem :push           upload the logs for this run (best effort)
:push
%CURL% -T %LOG% "%SRV%/uploads/%ID%/%RUN%/ts.log" -o nul --max-time 60 >nul 2>&1
if exist %PDT%\dism.log %CURL% -T %PDT%\dism.log "%SRV%/uploads/%ID%/%RUN%/dism.log" -o nul --max-time 120 >nul 2>&1
exit /b 0
