@echo off
rem env.cmd - all the state of the task sequence. deploy.cmd and every step
rem "call" it first, so a step typed at the WinPE prompt behaves exactly as it
rem does inside the sequence. No setlocal: it sets variables in the caller.
set PDT=X:\pdt
set LOG=%PDT%\ts.log
set CURL=curl.exe -sS
set BEACON_RETRY=3
rem DISM's log: on the RAM disk until the Windows partition exists, then on it
rem (W:\Scratch is removed by 60-unattend). One cumulative update produced a
rem 444 MB dism.log; X: must not be where that lands.
set DISMLOG=%PDT%\dism.log
if exist W:\Scratch set DISMLOG=W:\Scratch\dism.log

rem Who we are and where the server is: generated by the server at boot from
rem what iPXE saw (SRV, ID, MAC). The run token and model slug: minted once
rem per boot by deploy.cmd.
call %SystemRoot%\System32\id.cmd
if exist %PDT%\run.cmd call %PDT%\run.cmd
set MODEL=
if exist %PDT%\model.cmd call %PDT%\model.cmd

for %%k in (SystemManufacturer SystemProductName) do (
  for /f "tokens=2,*" %%a in ('reg query HKLM\HARDWARE\DESCRIPTION\System\BIOS /v %%k 2^>nul ^| find "%%k"') do set "%%k=%%b"
)
set "PRODUCT=%SystemProductName%"

rem Drive letters the steps rely on; assigned by ts\diskpart\*.txt.
rem   S: EFI system partition   W: Windows   R: recovery

rem Defaults.
set MODE=shell
set IMAGE=base.wim
set UNATTEND=default.xml
set DISKPART=uefi-gpt.txt
set DRIVERS=
set UPDATES=
set POST=
set ROLE=
set STOP_BEFORE=
set STOP_AFTER=
set REFERENCE=

rem Model defaults (models/<slug>.cfg). Deliberately NOT allowed here: MODE and
rem STOP_*. A model file must never be able to get a machine wiped.
if exist %PDT%\model.cfg for /f "usebackq eol=# tokens=1,* delims==" %%a in ("%PDT%\model.cfg") do (
  for %%k in (IMAGE UNATTEND DISKPART DRIVERS UPDATES POST ROLE) do if /i "%%a"=="%%k" set "%%k=%%b"
)
rem This machine (machines/<id>.cfg): the only place MODE can come from.
if exist %PDT%\machine.cfg for /f "usebackq eol=# tokens=1,* delims==" %%a in ("%PDT%\machine.cfg") do (
  for %%k in (MODE IMAGE UNATTEND DISKPART DRIVERS UPDATES POST ROLE STOP_BEFORE STOP_AFTER REFERENCE) do if /i "%%a"=="%%k" set "%%k=%%b"
)
exit /b 0
