#!/bin/bash
# 07-setup-physical.sh - Generalize the PXE install to real (physical) machines.
#
# The VM path (06-boot-vm.sh) uses QEMU's built-in DHCP + TFTP and the magic
# 10.0.2.2 host address. A physical target on a real LAN has neither, so this
# script stands up the equivalent on the host:
#
#   * dnsmasq in PROXY-DHCP mode  -> coexists with the LAN's existing DHCP server
#     (your router keeps handing out IP addresses; dnsmasq only answers the PXE
#     boot portion and serves ipxe.efi over TFTP).
#   * ipxe.efi rebuilt to chain to the host's real LAN IP (not 10.0.2.2).
#   * boot.ipxe + nginx regenerated to serve from the host's real LAN IP.
#
# Boot chain on the physical target (UEFI):
#   firmware PXE -> dnsmasq (proxy-DHCP offer + TFTP) -> ipxe.efi
#     -> HTTP http://<HOST_IP>:<PORT>/boot.ipxe -> wimboot -> WinPE -> Setup
#
# Override autodetection with env vars: HOST_IP, LAN_IF, LAN_NET.
# Skip the (slow) iPXE rebuild with SKIP_IPXE_REBUILD=1 (only safe if ipxe.efi was
# already built for THIS HOST_IP).
#
# Undo everything with scripts/99-teardown.sh.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$PROJECT_ROOT"
source "$PROJECT_ROOT/config.sh"

echo "=== Set up PXE for physical machines (dnsmasq) ==="

# --- Detect network parameters (override via env) ---
LAN_IF="${LAN_IF:-$(ip route show default 2>/dev/null | awk '/default/ {print $5; exit}')}"
HOST_IP="${HOST_IP:-$(ip route get 1.1.1.1 2>/dev/null | awk '{print $7; exit}')}"

if [[ -z "$LAN_IF" || -z "$HOST_IP" ]]; then
    echo "ERROR: could not autodetect the LAN interface / host IP." >&2
    echo "       Set them explicitly, e.g.:  LAN_IF=eth0 HOST_IP=192.168.1.10 $0" >&2
    exit 1
fi

# Connected subnet network address (for dnsmasq proxy range), computed from the
# interface's CIDR with python3 (a project dependency).
LAN_CIDR="$(ip -o -f inet addr show "$LAN_IF" | awk '{print $4; exit}')"
LAN_NET="${LAN_NET:-$(python3 -c "import ipaddress,sys; print(ipaddress.ip_network('$LAN_CIDR', strict=False).network_address)" 2>/dev/null)}"

if [[ -z "$LAN_NET" ]]; then
    echo "ERROR: could not determine subnet for $LAN_IF ($LAN_CIDR). Set LAN_NET=..." >&2
    exit 1
fi

echo "  Interface : $LAN_IF"
echo "  Host IP   : $HOST_IP"
echo "  Subnet    : $LAN_NET  (from $LAN_CIDR)"
echo ""
echo "dnsmasq will run in PROXY-DHCP mode — it will NOT hand out IP addresses and"
echo "is safe to run alongside your router's DHCP. It only answers PXE boot requests."
echo ""

# --- Ensure dnsmasq is installed ---
if ! command -v dnsmasq &>/dev/null; then
    echo "Installing dnsmasq..."
    sudo apt-get install -y dnsmasq
fi

# --- Rebuild ipxe.efi to chain to the host's real LAN IP ---
# The embedded chain target is baked in at build time (it runs before any of our
# HTTP config exists), so a VM-built ipxe.efi (chaining to 10.0.2.2) is useless on
# a physical LAN. Rebuild it pointing at HOST_IP.
if [[ "${SKIP_IPXE_REBUILD:-0}" == "1" ]]; then
    echo "SKIP_IPXE_REBUILD=1 — assuming pxe/ipxe.efi already targets $HOST_IP."
    [[ -f pxe/ipxe.efi ]] || { echo "ERROR: pxe/ipxe.efi missing; cannot skip rebuild." >&2; exit 1; }
else
    echo "Rebuilding pxe/ipxe.efi to chain to http://$HOST_IP:$HTTP_PORT/boot.ipxe ..."
    IPXE_CHAIN_HOST="$HOST_IP" bash "$SCRIPT_DIR/00c-build-ipxe.sh"
fi

# --- Regenerate boot.ipxe + (re)start nginx bound to the host LAN IP ---
echo "Regenerating boot.ipxe + nginx for HTTP host $HOST_IP ..."
HTTP_HOST="$HOST_IP" bash "$SCRIPT_DIR/04-setup-http.sh"

# --- Write the dnsmasq config ---
DNSMASQ_CONF="$PROJECT_ROOT/pxe/dnsmasq.conf"
TFTP_ROOT="$PROJECT_ROOT/pxe"
echo "Writing dnsmasq config: $DNSMASQ_CONF"
cat > "$DNSMASQ_CONF" <<EOF
# Auto-generated by 07-setup-physical.sh — PROXY-DHCP + TFTP for PXE installs.
# Coexists with the LAN's existing DHCP server; hands out NO IP addresses.

# Only listen on the install LAN interface, and don't run a DNS server.
interface=$LAN_IF
bind-interfaces
port=0
log-dhcp

# Serve ipxe.efi (and friends) over TFTP from the project's pxe/ directory.
enable-tftp
tftp-root=$TFTP_ROOT

# Proxy-DHCP on the connected subnet: answer only the PXE/boot portion.
dhcp-range=$LAN_NET,proxy

# Recognize iPXE (DHCP option 175) and UEFI x86-64 firmware (client-arch 7 or 9).
dhcp-match=set:ipxe,175
dhcp-match=set:efi64,option:client-arch,7
dhcp-match=set:efi64,option:client-arch,9

# UEFI x86-64 firmware that is NOT yet iPXE -> boot ipxe.efi over TFTP.
# (ipxe.efi's embedded script then chains to http://$HOST_IP:$HTTP_PORT/boot.ipxe.)
pxe-service=tag:efi64,tag:!ipxe,x86-64_EFI,"Windows 11 PXE install",ipxe.efi
EOF

# Validate the config before trying to run it.
echo "Validating dnsmasq config..."
sudo dnsmasq --test -C "$DNSMASQ_CONF"

cat <<EOF

dnsmasq config is valid. To start it (foreground, Ctrl-C to stop):

    sudo dnsmasq --no-daemon -C "$DNSMASQ_CONF"

or in the background:

    sudo dnsmasq -C "$DNSMASQ_CONF" --pid-file="$TFTP_ROOT/dnsmasq.pid"

NOTE: if a system dnsmasq is already running it may bind port 67/69 and conflict.
      Stop it first ('sudo systemctl stop dnsmasq') or rely on 99-teardown.sh.

Firewall: allow inbound UDP 67 + 4011 (proxy-DHCP), UDP 69 (TFTP), and
          TCP $HTTP_PORT (HTTP) on $LAN_IF.

On the physical target (UEFI firmware settings):
  1. Enable UEFI network/PXE boot (IPv4); keep Secure Boot capable.
  2. Put "UEFI: <NIC> IPv4 PXE" first in the boot order (or use the one-time boot menu).
  3. Power on — it will PXE -> ipxe.efi -> WinPE and install unattended.

WARNING: this wipes disk 0 of the target (answer/autounattend.xml). Be sure the
         right machine boots from the network.
EOF
