# AppArmor: allow /home/sqs/scripts/Windows-install-via-Linux/bin/lab-netns to create unprivileged user namespaces on a host
# where kernel.apparmor_restrict_unprivileged_userns=1 (the same shape Ubuntu
# uses for browsers and container tools). Generated by bin/lab-netns profile.
abi <abi/4.0>,
include <tunables/global>

profile pdt-lab-netns /home/sqs/scripts/Windows-install-via-Linux/bin/lab-netns flags=(unconfined) {
  userns,

  include if exists <local/pdt-lab-netns>
}
